services:
  asr:
    build: ./asr
    container_name: whisper-asr
    ports:
      - "6000:6000"
    volumes:
      - asr_data:/root/.cache
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  tts:
    image: ghcr.io/coqui-ai/tts
    container_name: coqui-tts

    ports:
      - "5002:5002"

    entrypoint: ["python3", "TTS/server/server.py"]

    command:
      - "--model_path"
      - "/model/model_file.pth"
      - "--config_path"
      - "/model/config.json"
      - "--use_cuda"
      - "false"

    volumes:
      - ./tts/bn_v4:/model:ro
      - ./tts/server.py:/root/TTS/server/server.py:ro


    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  chatbot:
    build: ./chatbot
    container_name: chatbot
    ports:
      - "9000:9000"
    volumes:
      - ./chatbot:/app

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]    
volumes:
  asr_data:
